// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXcjIXPsD04cplaEln34BmBZor7PtLEbs',
    appId: '1:240566440039:web:a5099a4bbe9856b909c4c2',
    messagingSenderId: '240566440039',
    projectId: 'dosemate-65db9',
    authDomain: 'dosemate-65db9.firebaseapp.com',
    storageBucket: 'dosemate-65db9.firebasestorage.app',
    measurementId: 'G-M4BK8645KM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmiuOjNU50Rgn7r38iUsv-1PnNmOvZtN0',
    appId: '1:240566440039:android:cdb5784717d0059709c4c2',
    messagingSenderId: '240566440039',
    projectId: 'dosemate-65db9',
    storageBucket: 'dosemate-65db9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZz4KkVEmaEJCRTKlxXP6HM-EQeGWxyRQ',
    appId: '1:240566440039:ios:4ce13b55ae5f220709c4c2',
    messagingSenderId: '240566440039',
    projectId: 'dosemate-65db9',
    storageBucket: 'dosemate-65db9.firebasestorage.app',
    iosBundleId: 'com.example.dosemate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZz4KkVEmaEJCRTKlxXP6HM-EQeGWxyRQ',
    appId: '1:240566440039:ios:4ce13b55ae5f220709c4c2',
    messagingSenderId: '240566440039',
    projectId: 'dosemate-65db9',
    storageBucket: 'dosemate-65db9.firebasestorage.app',
    iosBundleId: 'com.example.dosemate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXcjIXPsD04cplaEln34BmBZor7PtLEbs',
    appId: '1:240566440039:web:db1b08308c875de409c4c2',
    messagingSenderId: '240566440039',
    projectId: 'dosemate-65db9',
    authDomain: 'dosemate-65db9.firebaseapp.com',
    storageBucket: 'dosemate-65db9.firebasestorage.app',
    measurementId: 'G-KY1E3K3M7W',
  );
}
